export type Mss = {
    EDGE: string,
    LinkMgcf: string,
    PornNumberE1: string,
    SignalType: string,
    DPC: string,
    TS: string,
    SL: string,
    MctetGctet: string,
    District: string,
    City: string,
    ObjMss: string,
    TrunkGroup: string,
    TransportSDH: string,
    Prefix: string,
    ContactSideB: string,
    State: string,
    CommissioningDate: string,
    BaseDoc: string,
    Comment: string,
};